// <auto-generated />
namespace FireStation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class sajjad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sajjad));
        
        string IMigrationMetadata.Id
        {
            get { return "202106260332121_sajjad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
