//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireStation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FireStationEntities : DbContext
    {
        public FireStationEntities()
            : base("name=FireStationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Accident> tbl_Accident { get; set; }
        public virtual DbSet<tbl_AccidentEmplyoee> tbl_AccidentEmplyoee { get; set; }
        public virtual DbSet<tbl_AccidentInjured> tbl_AccidentInjured { get; set; }
        public virtual DbSet<tbl_AccidentM> tbl_AccidentM { get; set; }
        public virtual DbSet<tbl_AccidentO> tbl_AccidentO { get; set; }
        public virtual DbSet<tbl_AccidentStation> tbl_AccidentStation { get; set; }
        public virtual DbSet<tbl_AccidentType> tbl_AccidentType { get; set; }
        public virtual DbSet<tbl_Cause> tbl_Cause { get; set; }
        public virtual DbSet<tbl_Employee> tbl_Employee { get; set; }
        public virtual DbSet<tbl_Injured> tbl_Injured { get; set; }
        public virtual DbSet<tbl_Leave> tbl_Leave { get; set; }
        public virtual DbSet<tbl_Material> tbl_Material { get; set; }
        public virtual DbSet<tbl_Missives> tbl_Missives { get; set; }
        public virtual DbSet<tbl_Organizations> tbl_Organizations { get; set; }
        public virtual DbSet<tbl_Repair> tbl_Repair { get; set; }
        public virtual DbSet<tbl_shift> tbl_shift { get; set; }
        public virtual DbSet<tbl_ShiftEmployee> tbl_ShiftEmployee { get; set; }
        public virtual DbSet<tbl_ShiftRegister> tbl_ShiftRegister { get; set; }
        public virtual DbSet<tbl_State> tbl_State { get; set; }
        public virtual DbSet<tbl_Usage> tbl_Usage { get; set; }
        public virtual DbSet<tbl_weather> tbl_weather { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
