//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccidentEmplyoee
    {
        public int AEId { get; set; }
        public int EmployeeId { get; set; }
        public int AccidentId { get; set; }
    
        public virtual tbl_Accident tbl_Accident { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
