//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Injured
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Injured()
        {
            this.tbl_AccidentInjured = new HashSet<tbl_AccidentInjured>();
        }
    
        public int InjuredID { get; set; }
        public string InjuredName { get; set; }
        public string InjuredLastName { get; set; }
        public bool InjuredSex { get; set; }
        public bool InjuredType { get; set; }
        public bool InjuredTypeinjury { get; set; }
        public string InjuredDescription { get; set; }
        public string InjuredLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AccidentInjured> tbl_AccidentInjured { get; set; }
    }
}
