//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireStation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_shift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_shift()
        {
            this.tbl_ShiftEmployee = new HashSet<tbl_ShiftEmployee>();
            this.tbl_ShiftRegister = new HashSet<tbl_ShiftRegister>();
        }
        [Display(Name = "شناسه شیفت")]
        public int ShiftId { get; set; }
        [Display(Name = "عنوان شیفت")]
        public string ShiftName { get; set; }
        [Display(Name = "شناسه ایستگاه")]
        public int StateId { get; set; }
    
        public virtual tbl_State tbl_State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ShiftEmployee> tbl_ShiftEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ShiftRegister> tbl_ShiftRegister { get; set; }
    }
}
