//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Leave
    {
        public int LeaveID { get; set; }
        public int ShiftEmployeeId { get; set; }
        public int ShiftRegisterId { get; set; }
        public int EmployeeID1 { get; set; }
        public Nullable<int> EmployeeID2 { get; set; }
    
        public virtual tbl_Employee tbl_Employee { get; set; }
        public virtual tbl_Employee tbl_Employee1 { get; set; }
        public virtual tbl_ShiftEmployee tbl_ShiftEmployee { get; set; }
        public virtual tbl_ShiftRegister tbl_ShiftRegister { get; set; }
    }
}
