//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Missives
    {
        public int MissiveId { get; set; }
        public string MissiveTitel { get; set; }
        public string MissiveText { get; set; }
        public string MissiveFileUrl { get; set; }
        public System.DateTime MissiveDate { get; set; }
        public string MissiveNumber { get; set; }
        public int MissiveUserId { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
    }
}
