//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireStation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Material()
        {
            this.tbl_AccidentM = new HashSet<tbl_AccidentM>();
            this.tbl_Repair = new HashSet<tbl_Repair>();
        }
        [Display(Name = "شناسه")]
        public int MaterialId { get; set; }
        [Display(Name = "کد اموال")]
        public string MaterialCode { get; set; }
        [Display(Name = "نام تجهیزات")]
        public string MaterialName { get; set; }
        [Display(Name = "تصویر")]
        public string MaterialPic { get; set; }
        [Display(Name = "نوع تجهیزات")]
        public string MaterialType { get; set; }
        [Display(Name = "واحد")]
        public string MaterialVahed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AccidentM> tbl_AccidentM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Repair> tbl_Repair { get; set; }
    }
}
