//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireStation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_ShiftRegister
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ShiftRegister()
        {
            this.tbl_Leave = new HashSet<tbl_Leave>();
        }
        [Display(Name = "شناسه گزارش روزانه")]
        public int ShiftRegisterid { get; set; }
        [Display(Name = "متن گزارش")]
        public string ShiftRegisterDec { get; set; }
        [Display(Name = "فرمانده شیفت")]
        public int ShiftRegisterCommandor { get; set; }
        [Display(Name = "زمان شروع")]
        public System.TimeSpan ShiftRegisterTimeStart { get; set; }
        [Display(Name = "زمان پایان")]
        public System.TimeSpan ShiftRegisterTimeEnd { get; set; }
        [Display(Name = "تاریخ شروع")]
        public System.DateTime ShiftRegisterDateStart { get; set; }
        [Display(Name = "تاریخ پایان")]
        public System.DateTime ShiftRegisteridDateEnd { get; set; }
        [Display(Name = "فایل اسکن شده گذارش")]
        public string ShiftRegisterurl { get; set; }
        [Display(Name = "شناسه شیفت")]
        public int ShiftRegisterShifId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Leave> tbl_Leave { get; set; }
        public virtual tbl_shift tbl_shift { get; set; }
    }
}
