//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ShiftRegister
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ShiftRegister()
        {
            this.tbl_Leave = new HashSet<tbl_Leave>();
        }
    
        public int ShiftRegisterid { get; set; }
        public string ShiftRegisterDec { get; set; }
        public int ShiftRegisterCommandor { get; set; }
        public System.TimeSpan ShiftRegisterTimeStart { get; set; }
        public System.TimeSpan ShiftRegisterTimeEnd { get; set; }
        public System.DateTime ShiftRegisterDateStart { get; set; }
        public System.DateTime ShiftRegisteridDateEnd { get; set; }
        public string ShiftRegisterurl { get; set; }
        public int ShiftRegisterShifId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Leave> tbl_Leave { get; set; }
        public virtual tbl_shift tbl_shift { get; set; }
    }
}
