//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireStation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Accident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Accident()
        {
            this.tbl_AccidentEmplyoee = new HashSet<tbl_AccidentEmplyoee>();
            this.tbl_AccidentInjured = new HashSet<tbl_AccidentInjured>();
            this.tbl_AccidentM = new HashSet<tbl_AccidentM>();
            this.tbl_AccidentO = new HashSet<tbl_AccidentO>();
            this.tbl_AccidentStation = new HashSet<tbl_AccidentStation>();
        }
        [Display(Name = "شماره حادثه")]
        public int AccidentId { get; set; }
        [Display(Name = "آدرس محل حادثه")]
        public string AccidentEventLocation { get; set; }
        [Display(Name = "توضیحات علت حادثه")]
        public string AccidentDescrption { get; set; }
        [Display(Name = "زمان اعلام حادثه")]
        public System.TimeSpan AccidentTime { get; set; }
        [Display(Name = "تاریخ وقوع حادثه")]
        public System.DateTime AccidentDate { get; set; }
        [Display(Name = "فایل گزارش حادثه")]
        public string AccidentReportUrl { get; set; }
        [Display(Name = " شرایط جوی")]
        public int AccidentWid { get; set; }
        [Display(Name = "نوع حادثه")]
        public int AccidentTypeId { get; set; }
        [Display(Name = "منطقه")]
        public int AccidentZone { get; set; }
        [Display(Name = "کاربر ثبت کننده")]
        public int AccidentUserId { get; set; }
        [Display(Name = "نوع کاربری")]
        public int AccidentUsageId { get; set; }
        [Display(Name = "زمان شروع عملیات")]
        public System.TimeSpan AccidentTimeStartOperation { get; set; }
        [Display(Name = "زمان خاتمه عملیات")]
        public System.TimeSpan AccidentTimeEndOperation { get; set; }
        [Display(Name = "زمان پاکسازی عملیات")]
        public Nullable<System.TimeSpan> AccidentTimeToClear { get; set; }
        [Display(Name = "گزارش دهنده ")]
        public string AccidentReporter { get; set; }
        [Display(Name = "خبر گیرنده")]
        public int AccidentReportReciver { get; set; }
        [Display(Name = "روش خبر رسانی")]
        public int AccidentReportType { get; set; }
        [Display(Name = "تعداد طبقات")]
        public Nullable<int> AccidentSiteFloors { get; set; }
        [Display(Name = "نوع ساختمان")]
        public string AccidentBuildingType { get; set; }
        [Display(Name = "مالک ساختمان")]
        public string AccidentBuildingOwner { get; set; }
        [Display(Name = "تلفن")]
        public string AccidentBuildingTel { get; set; }
        [Display(Name = "مستاجر ساختمان")]
        public string AccidentBuildingTenant { get; set; }
        [Display(Name = "سایر موارد")]
        public string AccidentOtherType { get; set; }
        [Display(Name = "اقدامات اولیه")]
        public string AccidentPreliminaryMeasures { get; set; }
        [Display(Name = "شرح عملیات ")]
        public string AccidentDescriptionOperation { get; set; }
        [Display(Name = "شرح خسارات وارده به تجهیزات")]
        public string AccidentDamageDescriptionO { get; set; }
        [Display(Name = "شرح خسارات وارده به محل")]
        public string AccidentDamageDescriptionL { get; set; }
        [Display(Name = "تهیه کننده گزارش")]
        public int AccidentReportProducer { get; set; }
        [Display(Name = "فرمانده عملیات")]
        public int AccidentOperationsCommander { get; set; }
        [Display(Name = "تاریخ ثبت")]
        public System.DateTime DateAdd { get; set; }
        [Display(Name = "شرح خسارات وارده به تجهیزات")]
        public string AccidentOperationProblems { get; set; }
        [Display(Name = "علت حادثه")]
        public int AccidentCause { get; set; }
        public bool Isdelete { get; set; }
    
        public virtual tbl_AccidentType tbl_AccidentType { get; set; }
        public virtual tbl_Cause tbl_Cause { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
        public virtual tbl_Employee tbl_Employee1 { get; set; }
        public virtual tbl_Usage tbl_Usage { get; set; }
        public virtual tbl_weather tbl_weather { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AccidentEmplyoee> tbl_AccidentEmplyoee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AccidentInjured> tbl_AccidentInjured { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AccidentM> tbl_AccidentM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AccidentO> tbl_AccidentO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AccidentStation> tbl_AccidentStation { get; set; }
    }
}
