//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireStation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Missives
    {
        [Display(Name = "شناسه بخشنامه")]
        public int MissiveId { get; set; }
        [Display(Name = "عنوان بخشنامه")]
        public string MissiveTitel { get; set; }
        [Display(Name = "متن بخشنامه")]
        public string MissiveText { get; set; }
        [Display(Name = "فایل بخشنامه")]
        public string MissiveFileUrl { get; set; }
        [Display(Name = "تاریخ بخشنامه")]
        public System.DateTime MissiveDate { get; set; }
        [Display(Name = "شماره بخشنامه")]
        public string MissiveNumber { get; set; }
        [Display(Name = "کاربر ثبت کننده ")]
        public int MissiveUserId { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
    }
}
